configfile: "config/config.yaml"

##### load rules #####

include: "rules/common.smk"
include: "rules/trim.smk"
include: "rules/braker.smk"

workdir: config['outdir']

rule all:
    input:
        expand("{genome}/braker/braker.gff3", genome=GENOMES["genome_id"])
        # expand("trimmed/{sample}_P_R1.fastq.gz", sample=SAMPLES["sample_name"])
