configfile: "config/config.yaml"

##### load rules #####

include: "rules/common.smk"
include: "rules/trim.smk"
# include: "rules/qc.smk"
# include: "rules/align.smk"
# include: "rules/diffexp.smk"


workdir: config['outdir']

rule all:
    input:
        expand("trimmed/{sample}_P_R1.fastq.gz", sample=SAMPLES)
        # f"busco/{genome}.genome.out",
        # f"busco/{genome}.transcriptome.out"
