configfile: "config/config.yaml"

##### load rules #####

include: "rules/common.smk"
include: "rules/trim.smk"
include: "rules/braker.smk"

SAMPLES = pd.read_table(config["samples"],header=0,delim_whitespace=True).set_index("sample_name", drop=False)
GENOMES = pd.read_table(config["genomes"],header=0,delim_whitespace=True).set_index("genome_id", drop=False)

workdir: config['outdir']

rule all:
    input:
        expand("{genome}/braker_smk/braker.gff3", genome=GENOMES["genome_id"]),
        expand("trimmed/{sample}_P_R1.fastq.gz", sample=SAMPLES["sample_name"])
